// lib/services/states/taskStates/start_sales_journey.dart

import 'package:salesmanapp/database/app_database.dart';
//import 'package:salesmanapp/api/api_service.dart';
import 'package:uuid/uuid.dart';
import 'dart:convert';
import 'package:salesmanapp/services/websocket/session_manager.dart';

class StartSalesJourneyState {
  //final ApiService _api = ApiService();
  final AppDatabase _db = AppDatabase.instance;

  Future<String> execute({
    required int userId,
    required String taskId,
    required String displayName, // Dealer Name
    String? dealerId,
    int? verifiedDealerId,
    double? startLat,
    double? startLng,
  }) async {
    // 1. Start LOCAL Journey (Offline First)
    // Capture the ACTUAL UUID generated by your Drift database!
    final journeyId = await _db.startLocalJourney(
      userId: userId,
      taskId: taskId,
      dealerId: dealerId,
      verifiedDealerId: verifiedDealerId,
      siteName: displayName,
      pjpId: null, 
    );

    // 2. Create Payload for Server
    // We don't need the heavy GeoTrackingPoint model here, just a clean map for the JSON payload
    final startPayload = {
      'journeyId': journeyId,
      'taskId': taskId,
      'userId': userId,
      'latitude': startLat ?? 0.0,
      'longitude': startLng ?? 0.0,
      'dealerId': dealerId,
      'verifiedDealerId': verifiedDealerId,
      'timestamp': DateTime.now().toIso8601String(),
    };

    // 4. Queue for Sync (Outbox Pattern)
    // We don't await the API call here to ensure UI is snappy and works offline
    await _db.enqueueOp(
      JourneyOpsQueueCompanion.insert(
        opId: const Uuid().v4(),
        journeyId: journeyId,
        userId: userId,
        type: 'START',
        payload: jsonEncode(startPayload),
        createdAt: DateTime.now(),
      ),
    ); 

    // Connect the socket for this user BEFORE syncing
    await SessionManager.instance.startSession(userId);
    
    // NOW Trigger the Sync
    SessionManager.instance.triggerSync();

    return journeyId;
  }
}