// lib/technicalSide/models/mason_pc_model.dart
class Mason {
  final String id;
  final String name;
  final String phoneNumber;
  
  // KYC & Status
  final String? kycDocumentName;
  final String? kycDocumentIdNum;
  final String? kycStatus; // 'none', 'pending', 'approved', 'rejected'
  
  // Loyalty & Tracking
  final int pointsBalance;
  final int? bagsLifted;
  final String? firebaseUid;
  
  // Referral
  final bool? isReferred;
  final String? referredByUser;
  final String? referredToUser;
  
  // Relations (Old Single IDs - kept for compatibility)
  final String? dealerId;
  final String? siteId;
  final int? userId; // TSO/Salesman ID

  Mason({
    required this.id,
    required this.name,
    required this.phoneNumber,
    this.kycDocumentName,
    this.kycDocumentIdNum,
    this.kycStatus,
    this.pointsBalance = 0,
    this.bagsLifted,
    this.firebaseUid,
    this.isReferred,
    this.referredByUser,
    this.referredToUser,
    this.dealerId,
    this.siteId,
    this.userId,
  });

  factory Mason.fromJson(Map<String, dynamic> json) {
    return Mason(
      id: json['id']?.toString() ?? '',
      name: json['name'] ?? '',
      phoneNumber: json['phoneNumber'] ?? '',
      
      kycDocumentName: json['kycDocumentName'],
      kycDocumentIdNum: json['kycDocumentIdNum'],
      kycStatus: json['kycStatus'],
      
      pointsBalance: int.tryParse(json['pointsBalance']?.toString() ?? '0') ?? 0,
      bagsLifted: int.tryParse(json['bagsLifted']?.toString() ?? ''),
      firebaseUid: json['firebaseUid'],
      
      isReferred: json['isReferred'] == true || json['isReferred'] == 'true',
      referredByUser: json['referredByUser'],
      referredToUser: json['referredToUser'],
      
      dealerId: json['dealerId'],
      siteId: json['siteId'],
      userId: int.tryParse(json['userId']?.toString() ?? ''),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // ID is usually generated by server, removing for safety during creation
      'name': name,
      'phoneNumber': phoneNumber,
      'kycDocumentName': kycDocumentName,
      'kycDocumentIdNum': kycDocumentIdNum,
      'kycStatus': kycStatus,
      'pointsBalance': pointsBalance,
      'bagsLifted': bagsLifted,
      'firebaseUid': firebaseUid,
      'isReferred': isReferred,
      'referredByUser': referredByUser,
      'referredToUser': referredToUser,
      'dealerId': dealerId,
      'siteId': siteId,
      'userId': userId,
    };
  }
}