// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmZ4Y0IrLsgXT7eUiFSkKL8EGKVsYMkc',
    appId: '1:1004141461365:web:d37bb962fa172a45f2dd3c',
    messagingSenderId: '1004141461365',
    projectId: 'bestauthotp',
    authDomain: 'bestauthotp.firebaseapp.com',
    storageBucket: 'bestauthotp.firebasestorage.app',
    measurementId: 'G-D6EE0BL0ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQ177qpFfzm1wVnZAKlJLYXgQdx4CfGo',
    appId: '1:1004141461365:android:62c203e2cd8af9f0f2dd3c',
    messagingSenderId: '1004141461365',
    projectId: 'bestauthotp',
    storageBucket: 'bestauthotp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2l2FyJRVSn1R1y_t9XtXbxP6QW_er79k',
    appId: '1:1004141461365:ios:1e236102e3231a06f2dd3c',
    messagingSenderId: '1004141461365',
    projectId: 'bestauthotp',
    storageBucket: 'bestauthotp.firebasestorage.app',
    iosBundleId: 'com.example.assetarchiverflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2l2FyJRVSn1R1y_t9XtXbxP6QW_er79k',
    appId: '1:1004141461365:ios:1e236102e3231a06f2dd3c',
    messagingSenderId: '1004141461365',
    projectId: 'bestauthotp',
    storageBucket: 'bestauthotp.firebasestorage.app',
    iosBundleId: 'com.example.assetarchiverflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmZ4Y0IrLsgXT7eUiFSkKL8EGKVsYMkc',
    appId: '1:1004141461365:web:d36511fa0116eb25f2dd3c',
    messagingSenderId: '1004141461365',
    projectId: 'bestauthotp',
    authDomain: 'bestauthotp.firebaseapp.com',
    storageBucket: 'bestauthotp.firebasestorage.app',
    measurementId: 'G-0MFT602VK2',
  );
}
