// lib/main.dart

// --- ✅ ADD THESE IMPORTS ---
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the Firebase CLI
// ---
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:assetarchiverflutter/screens/auth/login_screen.dart';
import 'package:assetarchiverflutter/screens/nav_screen.dart';
import 'package:flutter/material.dart';
import 'package:assetarchiverflutter/models/employee_model.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_radar/flutter_radar.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'package:assetarchiverflutter/widgets/app_theme.dart';
import 'package:assetarchiverflutter/widgets/theme_provider.dart';
import 'package:assetarchiverflutter/models/mason_model.dart';

// The new "portal" selection screen
import 'package:assetarchiverflutter/screens/auth/app_selector_screen.dart';
// The new "splash" screen that handles Salesforce auto-login
import 'package:assetarchiverflutter/screens/auth/salesforce_splash_screen.dart';

// Your new routes
import 'package:assetarchiverflutter/screens/auth/contractor_login_screen.dart';
import 'package:assetarchiverflutter/screens/contractor/kyc_onboarding_screen.dart';
import 'package:assetarchiverflutter/screens/admin/admin_dashboard_screen.dart';

// --- ✅ IMPORTS FOR THE NEW SCREENS ---
import 'package:assetarchiverflutter/screens/contractor/kyc_pending_screen.dart';
import 'package:assetarchiverflutter/screens/contractor/contractor_nav_screen.dart';
// (Make sure you have created the files from our previous step)


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- ✅ THE FIX ---
  // This MUST be called before any Firebase services are used.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // --- END FIX ---
  await FirebaseAppCheck.instance.activate(
    androidProvider: AndroidProvider.playIntegrity,
  );

  await dotenv.load(fileName: ".env");
  await Hive.initFlutter();

  final radarPublishableKey = dotenv.env['RADAR_API_KEY'];
  if (radarPublishableKey != null) {
    await Radar.initialize(radarPublishableKey);
    debugPrint("✅ Radar SDK Initialized Successfully.");
  } else {
    debugPrint(
      "❌ ERROR: RADAR_PUBLISHABLE_KEY not found in .env file. Tracking will fail.",
    );
  }

  runApp(
    ChangeNotifierProvider(
      create: (context) => ThemeProvider(),
      child: const MyApp(loggedInEmployee: null),
    ),
  );
}

class MyApp extends StatelessWidget {
  final Employee? loggedInEmployee;
  const MyApp({super.key, this.loggedInEmployee});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Modern App',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeProvider.themeMode,

      initialRoute: '/selector',

      routes: {
        '/selector': (context) => const AppSelectorScreen(),
        '/salesforce_login': (context) =>
            const SalesforceSplashScreen(), // This handles auto-login
        '/salesforce_login_page': (context) =>
            const LoginScreen(), // Your original email/pass form
        '/contractor_login': (context) =>
            const ContractorLoginScreen(), // The new OTP login form
      },

      onGenerateRoute: (settings) {
        if (settings.name == '/home') {
          final employee = loggedInEmployee ?? settings.arguments as Employee;
          return MaterialPageRoute(
            builder: (context) {
              return NavScreen(employee: employee); // Your existing app shell
            },
          );
        }

        if (settings.name == '/admin') {
          final employee = loggedInEmployee ?? settings.arguments as Employee;
          return MaterialPageRoute(
            builder: (context) {
              return AdminDashboardScreen(employee: employee);
            },
          );
        }

        // --- ⬇️ REPLACED WITH FULL KYC ROUTING LOGIC ⬇️ ---
        if (settings.name == '/contractor_home') {
          final arguments = settings.arguments;
          Mason mason; // <-- Correct type is Mason

          if (arguments is Map<String, dynamic>) {
            // Correct parsing: from the login screen's Map
            mason = Mason.fromJson(arguments);
          } else if (arguments is Mason) {
            // Correct: for hot-reload
            mason = arguments;
          } else {
            // Fallback
            return MaterialPageRoute(
              builder: (context) => const AppSelectorScreen(),
            );
          }

          // --- ✅ THIS IS THE FULL KYC ROUTING LOGIC ---
          // We check the mason's status and route accordingly
          switch (mason.kycStatus) {
            case 'approved':
              // User is fully approved -> Go to the main app
              return MaterialPageRoute(
                builder: (context) => ContractorNavScreen(mason: mason),
              );
            case 'pending':
              // User has submitted but is waiting -> Go to "Pending" screen
              return MaterialPageRoute(
                builder: (context) => const KycPendingScreen(),
              );
            case 'none':
            case 'rejected':
            default:
              // New user or rejected user -> Go to KYC form
              return MaterialPageRoute(
                builder: (context) => KycOnboardingScreen(mason: mason),
              );
          }
          // --- ⬆️ END OF NEW LOGIC ⬆️ ---
        }

        return null; // Handle unknown routes
      },
    );
  }
}