// lib/main.dart
import 'package:flutter/material.dart';
import 'package:assetarchiverflutter/models/employee_model.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_radar/flutter_radar.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'package:assetarchiverflutter/widgets/app_theme.dart';
import 'package:assetarchiverflutter/widgets/theme_provider.dart';

// --- ✅ 1. ADD FIREBASE IMPORTS ---
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI

// --- NEW IMPORTS FOR PORTALS ---
// NOTE: I'm fixing your paths based on your previous files
// Make sure these paths are correct for your project
import 'package:assetarchiverflutter/screens/auth/app_selector_screen.dart'; 
import 'package:assetarchiverflutter/screens/auth/salesforce_splash_screen.dart'; 
import 'package:assetarchiverflutter/screens/auth/login_screen.dart'; 
import 'package:assetarchiverflutter/screens/nav_screen.dart'; 

// Admin screens
import 'package:assetarchiverflutter/screens/admin/admin_login.dart'; 
import 'package:assetarchiverflutter/screens/admin/admin_nav_screen.dart';

// Contractor screens
import 'package:assetarchiverflutter/screens/contractor/contractor_login_screen.dart';
import 'package:assetarchiverflutter/screens/contractor/contractor_nav_screen.dart';
import 'package:assetarchiverflutter/screens/contractor/kyc_onboarding_screen.dart'; 

// --- FIX: IMPORT YOUR MASON MODEL ---
import 'package:assetarchiverflutter/models/mason_model.dart';
// --- END NEW IMPORTS ---


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- ✅ 2. PUT FIREBASE INIT BACK ---
  // This is the code that was missing
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  debugPrint("✅ Firebase Initialized Successfully.");
  // --- END FIREBASE INIT ---

  await dotenv.load(fileName: ".env");
  await Hive.initFlutter();

  final radarPublishableKey = dotenv.env['RADAR_API_KEY'];
  if (radarPublishableKey != null) {
    await Radar.initialize(radarPublishableKey);
    debugPrint("✅ Radar SDK Initialized Successfully.");
  } else {
    debugPrint("❌ ERROR: RADAR_PUBLISHABLE_KEY not found in .env file. Tracking will fail.");
  }
  
  runApp(
    ChangeNotifierProvider(
      create: (context) => ThemeProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Modern App',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeProvider.themeMode,

      initialRoute: '/',
      routes: {
        '/': (context) => const AppSelectorScreen(),
        '/salesforce_login': (context) => const SalesforceSplashScreen(),
        '/salesforce_login_page': (context) => const LoginScreen(),
        '/admin_login': (context) => const AdminLoginScreen(),
        '/contractor_login': (context) => const ContractorLoginScreen(),
      },
      onGenerateRoute: (settings) {
        
        // --- Salesforce NavScreen ---
        if (settings.name == '/home') {
          final employee = settings.arguments as Employee;
          return MaterialPageRoute(
            builder: (context) {
              return NavScreen(employee: employee);
            },
          );
        }

        // --- Admin NavScreen ---
        if (settings.name == '/admin') {
          final employee = settings.arguments as Employee;
          return MaterialPageRoute(
            builder: (context) {
              return AdminNavScreen(employee: employee);
            },
          );
        }

        // --- Contractor NavScreen (App Shell) ---
        if (settings.name == '/contractor_nav') {
          final mason = settings.arguments as Mason; 
          return MaterialPageRoute(
            builder: (context) {
              return ContractorNavScreen(mason: mason);
            },
          );
        }
        
        // --- ✅ 3. KYC ONBOARDING ROUTE ---
        // This is triggered when the user taps the new banner
        if (settings.name == '/kyc_onboarding_screen') {
          final mason = settings.arguments as Mason;
          return MaterialPageRoute(
            builder: (context) {
              // This uses the file you provided
              return KycOnboardingScreen(mason: mason);
            },
            fullscreenDialog: true, // Shows it as a pop-up modal
          );
        }

        return null;
      },
    );
  }
}