// lib/technicalSide/screens/forms/add_technical_pjp_form.dart
import 'dart:async'; // for Timer
import 'package:flutter/material.dart';
import 'package:salesmanapp/models/employee_model.dart';
import 'package:salesmanapp/models/pjp_model.dart';
import 'package:salesmanapp/technicalSide/models/sites_model.dart';
import 'package:salesmanapp/api/api_service.dart';
import 'dart:developer' as dev;

class AddTechnicalPjpForm extends StatefulWidget {
  final Employee employee;
  final VoidCallback onPjpCreated;

  const AddTechnicalPjpForm({
    super.key,
    required this.employee,
    required this.onPjpCreated,
  });

  @override
  State<AddTechnicalPjpForm> createState() => _AddTechnicalPjpFormState();
}

class _AddTechnicalPjpFormState extends State<AddTechnicalPjpForm> {
  final _formKey = GlobalKey<FormState>();
  final ApiService _apiService = ApiService();
  
  TechnicalSite? _selectedSite;
  final _descriptionController = TextEditingController();
  bool _isSubmitting = false;

  // --- FINTECH THEME PALETTE (Technical) ---
  static const Color _surfaceWhite  = Colors.white;
  static const Color _cardNavy      = Color(0xFF0F172A); // Deep Navy
  static const Color _textDark      = Color(0xFF111827); // Navy/Black
  static const Color _textGrey      = Color(0xFF6B7280); // Subtitle Grey
  static const Color _inputFill     = Color(0xFFF9FAFB); // Very light grey
  static const Color _accentGreen   = Color(0xFF10B981); 

  @override
  void dispose() {
    _descriptionController.dispose();
    super.dispose();
  }

  // --- Search Logic ---
  Future<void> _openSiteSearch() async {
    final TechnicalSite? result = await showDialog(
      context: context,
      builder: (context) => _ServerSiteSearchDialog(
        api: _apiService, 
        userId: int.parse(widget.employee.id)
      ),
    );
    if (result != null) {
      setState(() {
        _selectedSite = result;
      });
    }
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;
    
    if (_selectedSite == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('Please select a site.'), backgroundColor: Colors.orange));
      return;
    }

    // Basic Geo-validation
    if (_selectedSite!.latitude == 0.0 || _selectedSite!.longitude == 0.0) {
       ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('Selected site has invalid coordinates. Cannot create PJP.'),
          backgroundColor: Colors.red));
       return;
    }

    setState(() => _isSubmitting = true);

    try {
      final String displayName = '${_selectedSite!.siteName}, ${_selectedSite!.address}';
      // Format: Name|Lat|Lng
      final String visitData = '$displayName|${_selectedSite!.latitude}|${_selectedSite!.longitude}';

      final newPjp = Pjp(
        id: '', // Generated by backend
        planDate: DateTime.now(),
        userId: int.parse(widget.employee.id),
        createdById: int.parse(widget.employee.id),
        
        // Statuses
        status: 'PENDING', 
        verificationStatus: 'PENDING',
        
        areaToBeVisited: visitData,
        description: _descriptionController.text.isNotEmpty ? _descriptionController.text : null,
        
        siteId: _selectedSite!.id,
        siteName: _selectedSite!.siteName,
        dealerId: null, 
        
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await _apiService.createPjp(newPjp);

      widget.onPjpCreated();
      if (mounted) Navigator.pop(context);
      
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('Technical Visit Plan Created!'), backgroundColor: _accentGreen)); 
    } catch (e) {
      dev.log('Create Tech PJP Error: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text('Failed to create plan: $e'), backgroundColor: Colors.red));
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  // --- UI Helpers ---
  InputDecoration _inputDecoration(String label, IconData icon) {
    return InputDecoration(
      labelText: label,
      labelStyle: const TextStyle(color: _textGrey, fontWeight: FontWeight.w500),
      prefixIcon: Icon(icon, color: _textGrey, size: 20),
      filled: true,
      fillColor: _inputFill,
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: _cardNavy, width: 1.5),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
      child: Container(
        padding: const EdgeInsets.all(24.0),
        decoration: const BoxDecoration(
          color: _surfaceWhite,
          borderRadius: BorderRadius.vertical(top: Radius.circular(24.0)),
        ),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Drag Handle
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  margin: const EdgeInsets.only(bottom: 20),
                  decoration: BoxDecoration(color: Colors.grey[300], borderRadius: BorderRadius.circular(12)),
                ),
              ),

              const Text(
                'Plan New Visit',
                style: TextStyle(
                  color: _textDark, 
                  fontSize: 20, 
                  fontWeight: FontWeight.bold,
                  letterSpacing: -0.5,
                )
              ),
              const SizedBox(height: 24),
              
              // --- SITE SELECTOR (InkWell) ---
              InkWell(
                onTap: _openSiteSearch,
                borderRadius: BorderRadius.circular(12),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                  decoration: BoxDecoration(
                    color: _inputFill,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.transparent),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.location_city, color: _textGrey, size: 20),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          _selectedSite != null 
                            ? "${_selectedSite!.siteName} (${_selectedSite!.area ?? 'Unknown'})" 
                            : "Select Construction Site",
                          style: TextStyle(
                            color: _selectedSite != null ? _textDark : _textGrey,
                            fontWeight: _selectedSite != null ? FontWeight.w600 : FontWeight.w500,
                            fontSize: 16,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                      const Icon(Icons.search, color: _textGrey),
                    ],
                  ),
                ),
              ),
              
              const SizedBox(height: 16),
              
              // Description Input
              TextFormField(
                controller: _descriptionController,
                style: const TextStyle(color: _textDark, fontWeight: FontWeight.w500),
                decoration: _inputDecoration('Remarks / Purpose (Optional)', Icons.notes),
                maxLines: 2,
              ),
              
              const SizedBox(height: 32),
              
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isSubmitting ? null : _submitForm,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _cardNavy,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    elevation: 0,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _isSubmitting
                      ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                      : const Text(
                          'CREATE PLAN', 
                          style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1.0)
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// --- INTERNAL SEARCH DIALOG (Themed) ---
class _ServerSiteSearchDialog extends StatefulWidget {
  final ApiService api;
  final int userId;
  const _ServerSiteSearchDialog({required this.api, required this.userId});
  @override
  State<_ServerSiteSearchDialog> createState() => _ServerSiteSearchDialogState();
}

class _ServerSiteSearchDialogState extends State<_ServerSiteSearchDialog> {
  List<TechnicalSite> _sites = [];
  bool _isLoading = false;
  Timer? _debounce;

  static const Color _textDark = Color(0xFF111827);
  static const Color _textGrey = Color(0xFF6B7280);
  static const Color _inputFill = Color(0xFFF9FAFB);

  void _search(String query) {
    if (_debounce?.isActive ?? false) _debounce!.cancel();
    _debounce = Timer(const Duration(milliseconds: 500), () async {
      setState(() => _isLoading = true);
      try {
        final res = await widget.api.fetchTechnicalSites(userId: widget.userId, search: query);
        if (mounted) setState(() => _sites = res);
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    });
  }

  @override
  void initState() {
    super.initState();
    _search(""); 
  }

  @override
  void dispose() {
    _debounce?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Container(
        padding: const EdgeInsets.all(24),
        height: 400,
        width: double.maxFinite,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text("Select Site", style: TextStyle(color: _textDark, fontWeight: FontWeight.bold, fontSize: 18)),
            const SizedBox(height: 16),
            TextField(
              autofocus: true,
              style: const TextStyle(color: _textDark),
              decoration: const InputDecoration(
                hintText: "Search site...",
                hintStyle: TextStyle(color: _textGrey),
                prefixIcon: Icon(Icons.search, color: _textGrey),
                filled: true,
                fillColor: _inputFill,
                border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12)), borderSide: BorderSide.none),
              ),
              onChanged: _search,
            ),
            const SizedBox(height: 10),
            Expanded(
              child: _isLoading 
                ? const Center(child: CircularProgressIndicator()) 
                : _sites.isEmpty 
                  ? const Center(child: Text("No sites found", style: TextStyle(color: _textGrey)))
                  : ListView.separated(
                      itemCount: _sites.length,
                      separatorBuilder: (_, __) => const Divider(height: 1, color: Color(0xFFE5E7EB)),
                      itemBuilder: (ctx, i) => ListTile(
                        title: Text(_sites[i].siteName, style: const TextStyle(color: _textDark, fontWeight: FontWeight.w600)),
                        subtitle: Text("${_sites[i].address} • ${_sites[i].concernedPerson}", style: const TextStyle(color: _textGrey, fontSize: 12)),
                        onTap: () => Navigator.pop(context, _sites[i]),
                      ),
                    ),
            ),
            const SizedBox(height: 10),
            Align(
              alignment: Alignment.centerRight,
              child: TextButton(onPressed: () => Navigator.pop(context, null), child: const Text("CANCEL", style: TextStyle(color: _textGrey))),
            )
          ],
        ),
      ),
    );
  }
}